name: bpmn_dart
publish_to: "none"
version: 1.3.2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.17.0
  xml: ^6.1.0
  js: ^0.6.4
  universal_html: ^2.0.8

dev_dependencies:
  lints: ^2.0.0
  dart_code_metrics: ^4.21.2
  test: ^1.21.6
