name: bpmn_dart
publish_to: "none"
version: 1.6.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.17.0
  xml: ^6.2.2
  js: ^0.6.5
  universal_html: ^2.0.8

dev_dependencies:
  lints: ^2.0.1
  dart_code_metrics: ^5.1.0
  test: ^1.22.0
